DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 64  # Increased for dual GPU (32 per GPU)
  TEST:
    BATCH_SIZE: 200  # Increased for dual GPU (100 per GPU)
  NUM_WORKERS: 16   # Increased for dual GPU

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize", "compress_blur"]

OPTIM:
  NAME: "sgd"
  LR: 0.004  # Increased LR for larger batch size (linear scaling rule)
  MAX_EPOCH: 10
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5
  WEIGHT_DECAY: 0.0005

TRAIN:
  PRINT_FREQ: 5

MODEL:
  BACKBONE:
    NAME: "ViT-L/14"
